# Generated by Django 3.1.4 on 2021-01-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.ImageField(upload_to='plants'),
        ),
    ]
