# Generated by Django 3.1.4 on 2021-01-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_auto_20210103_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.ImageField(upload_to='static/plants'),
        ),
    ]
