# Generated by Django 3.1.4 on 2021-01-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0009_auto_20210104_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='items',
        ),
        migrations.AddField(
            model_name='ordered',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nursery.order'),
            preserve_default=False,
        ),
    ]
