# Generated by Django 3.1.4 on 2021-01-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0010_auto_20210104_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
