# Generated by Django 3.1.4 on 2021-01-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('nursery', '0011_ordered_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
