# Generated by Django 3.1.4 on 2021-01-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0012_nursery_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nursery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nursery.nursery'),
            preserve_default=False,
        ),
    ]
