# Generated by Django 3.1.4 on 2021-01-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('nursery', '0013_order_nursery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
